name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild .\PlatformGame.sln /p:Configuration=Release

    - name: Create artifact directory
      run: |
        mkdir ./artifact
        mkdir ./artifact/PlatformGame

    - name: Copy files
      run: copy ./build/PlatformGame/Release/win32/PlatformGame.exe ./artifact/PlatformGame

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-binary
        path: ./artifact
